[project]
name = "nsp"
version = "0.1.0"
description = "graphs coursework"
authors = [
    {name = "romuloAMR",email = "amr.rmulo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter (>=1.1.1,<2.0.0)",
    "networkx (>=3.5,<4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
